version: '3'

services:

  api:
    build: ./backend
    volumes:
    - ./backend/api:/app/app:ro
    - ./backend/db:/db
    command: ["app.main:app", "--reload", "--bind", "0.0.0.0:80"]
    env_file: secrets.env
    environment:
    - STRIPE_API_VERSION=2020-08-27
    - WEBSITE_HOST=http://localhost:8080
    - CURRENCY=eur
    ports:
    - 127.0.0.1:5000:80

  nginx:
    image: nginx:1.14-alpine
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./static:/static:ro
    ports:
    - 127.0.0.1:8080:80
